name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    uses: haobogu/rmk/.github/workflows/user_build.yml@rmk-v0.6.1
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
